---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	parse_intent(parse_intent)
	resolve_chain(resolve_chain)
	unsupported_response(unsupported_response)
	get_native_balance(get_native_balance)
	get_erc20_balance(get_erc20_balance)
	get_erc20_allowance(get_erc20_allowance)
	get_erc20_metadata(get_erc20_metadata)
	read_contract(read_contract)
	format_response(format_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> parse_intent;
	get_erc20_allowance --> format_response;
	get_erc20_balance --> format_response;
	get_erc20_metadata --> format_response;
	get_native_balance --> format_response;
	parse_intent -.-> resolve_chain;
	parse_intent -.-> unsupported_response;
	read_contract --> format_response;
	resolve_chain -.-> format_response;
	resolve_chain -.-> get_erc20_allowance;
	resolve_chain -.-> get_erc20_balance;
	resolve_chain -.-> get_erc20_metadata;
	resolve_chain -.-> get_native_balance;
	resolve_chain -.-> read_contract;
	format_response --> __end__;
	unsupported_response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
